// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiwbYSKFsFc6T5E9j_PZuBHK2bcMbREeI',
    appId: '1:201194262803:web:3fe64d4de8e1a043e4cae6',
    messagingSenderId: '201194262803',
    projectId: 'nutritrack-ebe15',
    authDomain: 'nutritrack-ebe15.firebaseapp.com',
    storageBucket: 'nutritrack-ebe15.firebasestorage.app',
    measurementId: 'G-FDBVVNDH2M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAGeY8lk4BCPmyEn2AROquKG-uwtwj8jE',
    appId: '1:201194262803:android:475d48ef89d0636ce4cae6',
    messagingSenderId: '201194262803',
    projectId: 'nutritrack-ebe15',
    storageBucket: 'nutritrack-ebe15.firebasestorage.app',
  );

}